spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.qhc.oa.entity
  mapper-locations: classpath:mapper/*.xml

fdfs:
  connect-timeout: 1500
  so-timeout: 500
  tracker-list:
    - 192.168.1.107:22122
  thumb-image:
    width: 150
    height: 150

#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
  level:
    com:
      qhc:
        oa:
          mapper: debug